<!DOCTYPE html>
<html>
<head>
    <title>Admission Letter</title>
    <style>
        body { font-family: sans-serif; }
        .header { text-align: center; margin-bottom: 50px; }
        .logo { width: 100px; height: auto; }
        .content { margin: 0 50px; }
        .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 12px; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h1>StudentDocs University</h1>
        <p>OFFICE OF THE REGISTRAR</p>
        <hr>
    </div>

    <div class="content">
        <p>Date: {{ date('F d, Y') }}</p>

        <h3>OFFICIAL ADMISSION LETTER</h3>

        <p>Dear <strong>{{ $student->user->name }}</strong>,</p>

        <p>We are pleased to inform you that you have been admitted into the <strong>{{ $student->program }}</strong> program at StudentDocs University for the {{ date('Y') }} Academic Session.</p>

        <p><strong>Student Number:</strong> {{ $student->student_number }}</p>

        <p>Your admission is provisional subject to the verification of your academic credentials. Please ensure you complete your registration and document submission on the student portal.</p>

        <p>Congratulations on your admission!</p>

        <br><br>
        <p>Sincerely,</p>
        <br>
        <p><strong>Registrar</strong><br>StudentDocs University</p>
    </div>

    <div class="footer">
        Generated by StudentDocs Portal on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
